buildscript {
    repositories {
        maven {
            url 'https://dl.bintray.com/giancosta86/Hephaestus'
        }

        jcenter()
    }

    dependencies {
        classpath 'info.gianlucacosta.moonlicense:moonlicense-gradle:4.3'
        classpath 'info.gianlucacosta.aurora:aurora:7.0'
        classpath 'com.github.maiflai:gradle-scalatest:0.12'
    }
}


apply plugin: 'scala'
apply plugin: 'com.github.maiflai.scalatest'
apply plugin: 'info.gianlucacosta.moonlicense'
apply plugin: 'info.gianlucacosta.aurora'


group = 'info.gianlucacosta.graphsj'
archivesBaseName = 'graphsj-scenarios'
version = '6.1'


description = 'GraphsJ - Example scenarios'

project.ext.facebookPage = 'https://www.facebook.com/graphsj'


dependencies {
    generatedCompile 'org.scala-lang:scala-library:2.11.8'

    compile 'org.scala-lang:scala-library:2.11.8'

    compile 'info.gianlucacosta.graphsj:graphsj-sdk:6.1'

    testCompile 'org.scalatest:scalatest_2.11:2.2.6'
    testRuntime 'org.pegdown:pegdown:1.6.0'
}


aurora {
    gitHubUser = 'giancosta86'

    author {
        name = 'Gianluca Costa'
        email = 'gianluca@gianlucacosta.info'
        url = 'http://gianlucacosta.info/'
    }
}


moonLicense {
    license = apache2

    productInfo {
        productName = 'GraphsJ - Scenarios'
        inceptionYear = 2009
        copyrightHolder = 'Gianluca Costa'
    }
}
