buildscript {
    repositories {
        //TODO! Del this!
        mavenLocal()

        mavenCentral()
    }

    dependencies {
        classpath 'info.gianlucacosta.aurora:aurora:10.0.0-SNAPSHOT'
        classpath 'com.github.maiflai:gradle-scalatest:0.12'
    }
}


apply plugin: 'scala'
apply plugin: 'maven'
apply plugin: 'com.github.maiflai.scalatest'
apply plugin: 'info.gianlucacosta.aurora'


group = 'info.gianlucacosta.graphsj'
archivesBaseName = 'graphsj-scenarios'
version = '7.0.0-SNAPSHOT'


description = 'GraphsJ - Example scenarios'

dependencies {
    compile 'org.scala-lang:scala-library:2.11.8'

    compile 'info.gianlucacosta.graphsj:graphsj-sdk:7.0.0-SNAPSHOT'

    testCompile 'org.scalatest:scalatest_2.11:2.2.6'
    testRuntime 'org.pegdown:pegdown:1.6.0'
}


aurora {
    gitHubUser = 'giancosta86'

    author {
        name = 'Gianluca Costa'
        email = 'gianluca@gianlucacosta.info'
        url = 'http://gianlucacosta.info/'
    }
}